AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  file-upload
  Sample SAM Template for file-upload

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 2

Resources:
  FileUploadFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: file-upload/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Events:
        FileUpload:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /upload
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ServerlessRestApi:
    Description: "API Gateway endpoint URL to trigger FileUploadFunction"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/upload/"
  FileUploadFunction:
    Description: "HFileUploadFunction ARN"
    Value: !GetAtt FileUploadFunction.Arn
  FileUploadFunctionIamRole:
    Description: "Implicit IAM Role created for FileUploadFunction"
    Value: !GetAtt FileUploadFunctionRole.Arn
