AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Create S3 Bucket & attach access policy
Resources:
  MediaBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: tzrajesh7-media
      AccessControl: Private
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ["Content-Type"]
            AllowedMethods: [GET, PUT]
            AllowedOrigins: ["*"]
            ExposedHeaders: [Date]
            Id: appCors
            MaxAge: 3600
      Tags:
        - Key: purpose
          Value: practice

Outputs:
  BucketName:
    Description: bucket name
    Value: !Ref MediaBucket
  BucketURL:
    Description: bucket url
    Value: !GetAtt MediaBucket.WebsiteURL
